---
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes

- name: Install dependencies
  apt:
    name: python3-psycopg2
    state: present
    update_cache: yes

- name: Start PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create WordPress database
  become_user: postgres
  postgresql_db:
    name: wordpress

- name: Create WordPress user
  become_user: postgres
  postgresql_user:
    name: wordpress
    password: "{{ db_password }}"
    db: wordpress
    priv: "ALL"
    state: present
