---
- name: Allow SSH, HTTP and HTTPS though the firewall
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443

- name: Enable Firewall
  community.general.ufw:
    state: enabled
    policy: deny
